name: 'SFDX Setup'
description: 'Salesforce setup action for installing the CLI and related plugins.'

inputs:
  plugins:
    description: Specify SF CLI plugins to be installed, e.g. "['@salesforce/lwc-dev-server','sfdx-git-delta']".
    required: false
  version:
    description: Specify SF CLI version to be installed, e.g. "2.32.8".
    required: false

runs:
  using: composite
  steps:
    - name: Install SF CLI
      shell: bash
      run: |
        if [[ -z "${{ inputs.version }}" ]]; then
          echo "No version specified, latest SF CLI version is installed..."
          npm i -g @salesforce/cli
        else
          echo "Installing SF CLI with version ${{ inputs.version }}..."
          npm i -g @salesforce/cli@${{ inputs.version }}
        fi

        sf version
    - name: Install Plugins
      if: ${{ inputs.plugins }}
      shell: bash
      run: |
        echo "Installing SF CLI plugins: ${{ join( fromJSON(inputs.plugins), ', ') }}"

        for i in ${{ join( fromJSON(inputs.plugins), ' ') }}
        do
          echo "Installing plugin $i..."
          echo y | sf plugins install $i
        done

        sf plugins
